version: '3.8'

services:
 orderdb:
  container_name: orderdb
  environment:
   SA_PASSWORD: "Asdf@1234"
   ACCEPT_EULA: "Y"
  restart: always
  volumes:
  - sqlserver_data:/var/lib/sqlserver/data
  ports:
  - "1435:1433"

 #productdb: mysql
 productdb:
  container_name: productdb
  environment:
   MYSQL_ROOT_PASSWORD: "Asdf@1234"
  restart: always
  volumes:
  - mysql_data:/var/lib/mysql
  ports:
  - "3307:3306"

 #customerdb: postgres
 customerdb:
  container_name: customerdb
  environment:
    - POSTGRES_USER=admin
    - POSTGRES_PASSWORD=admin1234
    - POSTGRES_DB=DiscountDb
  restart: always
  volumes:
  - postgres_data:/var/lib/postgresql/data
  ports:
  - "5433:5432"

 #basketdb: redis
 basketdb:
  container_name: basketdb
  restart: always
  ports:
  - "6380:6379"

 #inventorydb: mongo
 inventorydb:
  container_name: inventorydb
  restart: always
  ports:
  - "27018:27017"
  volumes:
  - mongo_data:/data/db

#infrastructure section

 rabbitmq:
  container_name: rabbitmq
  restart: always
  ports:
  - "5673:5672"
  - "15673:15672"

 pgadmin:
  container_name: pgadmin
  environment:
   - PGADMIN_DEFAULT_EMAIL=longdhn.lk@gmail.com
   - PGADMIN_DEFAULT_PASSWORD=Asdf@1234
  restart: always
  ports:
  - "5050:80"
  volumes:
  - pgadmin_data:/root/.pgadmin

 portainer:
  container_name: portainer
  restart: always
  ports:
  - "8000:8000"
  - "9000:9000"
  volumes:
  - /var/run/docker.sock:/var/docker.sock
  - portainer_data:/data

 elasticsearch:
  container_name: elasticsearch
  environment:
   - xpack.monitoring.enabled=true
   - xpack.watcher.enabled=false
   - discover.type=single-node
  ports:
  - "9201:9200"
  volumes:
  - elasticsearch_data:/usr/share/elasticsearch/data

 kibana:
  container_name: kibana
  environment:
   - ELASTICSEARCH_URL=http://elasticsearch:9201
  ports:
  - "5602:5601"
  depends_on:
  - elasticsearch


 

